listener.tcp.default = 0.0.0.0:1883
listener.http.default = 0.0.0.0:8080
allow_anonymous = off
password_file = /vernemq/etc/vmq.passwd
allow_multiple_sessions = on
log.console = console
log.console.level = info
accept_eula=yes
listener.ws.default=0.0.0.0:8080
log.console=console
allow_anonymous=off
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.tcp.default = 172.20.0.5:1883
listener.vmq.clustering = 172.20.0.5:44053
listener.http.metrics = 172.20.0.5:8888
accept_eula=yes
listener.ws.default=0.0.0.0:8080
log.console=console
allow_anonymous=off
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.tcp.default = 172.20.0.5:1883
listener.vmq.clustering = 172.20.0.5:44053
listener.http.metrics = 172.20.0.5:8888
accept_eula=yes
listener.ws.default=0.0.0.0:8080
log.console=console
allow_anonymous=off
erlang.distribution.port_range.minimum = 9100
erlang.distribution.port_range.maximum = 9109
listener.tcp.default = 172.20.0.5:1883
listener.vmq.clustering = 172.20.0.5:44053
listener.http.metrics = 172.20.0.5:8888
